# Generated by Django 5.1.6 on 2025-02-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indcric", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(default="wallet", max_length=20),
        ),
    ]
