# Generated by Django 5.1.6 on 2025-02-15 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cric_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="match",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="cric_users.match",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(default="wallet", max_length=20),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cric_users.match"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="payment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cric_users.payment",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cric_users.player"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team1",
                to="cric_users.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team2",
                to="cric_users.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winner",
                to="cric_users.team",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cric_users.team"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together={("user", "match")},
        ),
    ]
