# Generated by Django 5.1.6 on 2025-02-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cric_users",
            "0002_payment_match_payment_method_alter_attendance_match_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
