# Generated by Django 5.1.6 on 2025-02-16 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cric_users", "0003_alter_match_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="team1",
        ),
        migrations.RemoveField(
            model_name="match",
            name="team2",
        ),
        migrations.AddField(
            model_name="team",
            name="match",
            field=models.ForeignKey(
                default=100000,
                on_delete=django.db.models.deletion.CASCADE,
                to="cric_users.match",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winner",
                to="cric_users.team",
            ),
        ),
    ]
