# Generated by Django 5.1.6 on 2025-02-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cric_users",
            "0004_remove_match_team1_remove_match_team2_team_match_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="batsman", max_length=20),
        ),
        migrations.AlterField(
            model_name="player",
            name="role",
            field=models.CharField(max_length=20),
        ),
    ]
