# Generated by Django 5.1.6 on 2025-02-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cric_users", "0005_user_role_alter_player_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="attendance_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="cost_per_person",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
